export const states: Array<{ id: string; label: string }> = [
  { id: 'andhraPradesh', label: 'Andhra Pradesh' },
  { id: 'arunachalPradesh', label: 'Arunachal Pradesh' },
  { id: 'assam', label: 'Assam' },
  { id: 'bihar', label: 'Bihar' },
  { id: 'chhattisgarh', label: 'Chhattisgarh' },
  { id: 'goa', label: 'Goa' },
  { id: 'gujarat', label: 'Gujarat' },
  { id: 'haryana', label: 'Haryana' },
  { id: 'himachalPradesh', label: 'Himachal Pradesh' },
  { id: 'jharkhand', label: 'Jharkhand' },
  { id: 'karnataka', label: 'Karnataka' },
  { id: 'kerala', label: 'Kerala' },
  { id: 'madhyaPradesh', label: 'Madhya Pradesh' },
  { id: 'maharashtra', label: 'Maharashtra' },
  { id: 'manipur', label: 'Manipur' },
  { id: 'meghalaya', label: 'Meghalaya' },
  { id: 'mizoram', label: 'Mizoram' },
  { id: 'nagaland', label: 'Nagaland' },
  { id: 'odisha', label: 'Odisha' },
  { id: 'punjab', label: 'Punjab' },
  { id: 'rajasthan', label: 'Rajasthan' },
  { id: 'sikkim', label: 'Sikkim' },
  { id: 'tamilNadu', label: 'Tamil Nadu' },
  { id: 'telangana', label: 'Telangana' },
  { id: 'tripura', label: 'Tripura' },
  { id: 'uttarakhand', label: 'Uttarakhand' },
  { id: 'uttarPradesh', label: 'Uttar Pradesh' },
  { id: 'westBengal', label: 'West Bengal' },
  { id: 'chandigarh', label: 'Chandigarh' },
  { id: 'ladakh', label: 'Ladakh' },
  { id: 'puducherry', label: 'Puducherry' },
  { id: 'jammu&Kashmir', label: 'Jammu & Kashmir' },
  { id: 'delhi', label: 'Delhi' },
  { id: 'andamadAndNicobarIslands', label: 'Andaman and Nicobar Islands' },
];

export const whyYouShouldRent = [
  {
    id: 'one',
    title: 'Live Better Now',
    text: 'With our award-winning furniture, create your dream home today. Without waiting for that elusive tomorrow.',
  },
  {
    id: 'two',
    title: 'Value For Money',
    text: 'Bed or sofa? It’s not a choice anymore. With our pocket-friendly packages, you can have that perfect home at a fraction of the cost and effort.',
  },
  {
    id: 'three',
    title: 'Change, As Your Needs Evolve',
    text: 'Keep things flexible and change your furniture as your needs change.',
  },
];
